name: 构建并部署博客应用

on:
  push:
    branches: [ main ]  # 当推送到main分支时触发

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 设置QEMU
        uses: docker/setup-qemu-action@v2

      - name: 设置Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: 登录到DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 构建并推送前端镜像
        uses: docker/build-push-action@v3
        with:
          context: ./my_page_frontend
          file: ./my_page_frontend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/my-page-frontend:latest

      - name: 构建并推送后端镜像
        uses: docker/build-push-action@v3
        with:
          context: ./my_page_backend
          file: ./my_page_backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/my-page-backend:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      # 创建SSH密钥文件
      - name: 创建SSH密钥文件
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      # 创建部署脚本
      - name: 创建部署脚本
        run: |
          cat > deploy_remote.sh << 'EOF'
          #!/bin/bash
          # 登录到DockerHub
          echo $1 | docker login -u $2 --password-stdin
          
          # 拉取最新镜像
          docker pull $2/my-page-frontend:latest
          docker pull $2/my-page-backend:latest
          
          # 确保目录存在
          mkdir -p ~/my-page
          
          # 修改docker-compose.yml中的镜像引用
          cd ~/my-page
          sed -i "s|build: ./my_page_frontend|image: $2/my-page-frontend:latest|g" docker-compose.yml
          sed -i "s|build: ./my_page_backend|image: $2/my-page-backend:latest|g" docker-compose.yml
          
          # 停止并删除旧容器（如果存在）
          docker-compose down || true
          
          # 启动容器
          docker-compose up -d
          EOF

      # 复制文件到EC2
      - name: 复制文件到EC2
        run: |
          scp -o StrictHostKeyChecking=no docker-compose.yml ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:~/my-page/
          scp -o StrictHostKeyChecking=no deploy_remote.sh ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:~/

      # 执行远程部署命令
      - name: 执行远程部署命令
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} "chmod +x ~/deploy_remote.sh && ~/deploy_remote.sh '${{ secrets.DOCKERHUB_TOKEN }}' '${{ secrets.DOCKERHUB_USERNAME }}'"